# Generated by Django 3.2.13 on 2022-12-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('local', '0001_initial'),
        ('aseguramiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('cantidad_participantes', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacion', to='actividad.actividad')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='ReservacionAseguramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('aseguramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacionaseguramientos', to='aseguramiento.aseguramiento')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacionaseguramientos', to='reservacion.reservacion')),
            ],
            options={
                'verbose_name': 'ReservacionAseguramiento',
                'verbose_name_plural': 'ReservacionAseguramientos',
                'db_table': 'reservacion_aseguramiento',
            },
        ),
        migrations.AddField(
            model_name='reservacion',
            name='aseguramientos',
            field=models.ManyToManyField(through='reservacion.ReservacionAseguramiento', to='aseguramiento.Aseguramiento'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacion', to='local.local'),
        ),
    ]
