# Generated by Django 3.2.13 on 2022-12-23 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_actividad', '0001_initial'),
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='tipo_actividad.tipoactividad'),
        ),
    ]
